### ISSUE TITLE
Setup on Lxplus

### ISSUE THREAD

**Issue by JohanWulff** [uhh-cms/hh2bbtautau#15]
Dear *hh2bbtautau* developers, 

I'm trying to setup and run this code on `lxplus.cern.ch`. When running this sample task from the README.md:

```
law run cf.ReduceEvents \
    --version v1 \
    --dataset hh_ggf_bbtautau_madgraph \
    --branch 0
```
I run into this error:

```
ERROR: ... cf.GetDatasetLFNs(...)
Traceback (most recent call last):
  File "/eos/user/j/jowulff/hh2bbtautau/modules/columnflow/modules/law/law/target/remote/interface.py", line 120, in wrapper
    return func(self, *args, **kwargs)
  File "/eos/user/j/jowulff/hh2bbtautau/modules/columnflow/modules/law/law/contrib/gfal/target.py", line 312, in mkdir_rec
    raise e
law.contrib.gfal.target.GFALError_mkdir: globus_ftp_client: the server responded with an error 550 Permission denied    (GFALError_mkdir: unknown reason)
```

the call that raises the exception is:

```
  File "/eos/user/j/jowulff/hh2bbtautau/modules/columnflow/modules/law/law/contrib/gfal/target.py", line 305, in mkdir_rec
    ctx.mkdir_rec(uri, perm)
gfal2.GError: globus_ftp_client: the server responded with an error 550 Permission denied  
```

It seems like I don't have permissions for creating a directory.. Any help would be appreciated

**Comment by JohanWulff** [comment]
@riga @haddadanas Ping.

**Comment by riga** [comment]
Hey @JohanWulff , I think this should be fixed by now, but if not, I guess it's a permission error related to your proxy. Let's check in person in case this issue persists.
